USE [master]
GO

/****** Object:  Database [SGE]    Script Date: 3/02/2023 12:44:33 p. m. ******/
DROP DATABASE [SGE]
GO

/****** Object:  Database [SGE]    Script Date: 3/02/2023 12:44:33 p. m. ******/
CREATE DATABASE [SGE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SGE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SGE.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SGE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SGE_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SGE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SGE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SGE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SGE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SGE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SGE] SET ARITHABORT OFF 
GO

ALTER DATABASE [SGE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SGE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SGE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SGE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SGE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SGE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SGE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SGE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SGE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SGE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SGE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SGE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SGE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SGE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SGE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SGE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SGE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SGE] SET RECOVERY FULL 
GO

ALTER DATABASE [SGE] SET  MULTI_USER 
GO

ALTER DATABASE [SGE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SGE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SGE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SGE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SGE] SET  READ_WRITE 
GO

